/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesStoryIdReadRouteImport } from './routes/stories.$storyId.read'
import { Route as StoriesStoryIdEditRouteImport } from './routes/stories.$storyId.edit'
import { Route as StoriesStoryIdChaptersChapterIdEditRouteImport } from './routes/stories.$storyId.chapters.$chapterId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdReadRoute = StoriesStoryIdReadRouteImport.update({
  id: '/stories/$storyId/read',
  path: '/stories/$storyId/read',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdEditRoute = StoriesStoryIdEditRouteImport.update({
  id: '/stories/$storyId/edit',
  path: '/stories/$storyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdChaptersChapterIdEditRoute =
  StoriesStoryIdChaptersChapterIdEditRouteImport.update({
    id: '/stories/$storyId/chapters/$chapterId/edit',
    path: '/stories/$storyId/chapters/$chapterId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/read': typeof StoriesStoryIdReadRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/read': typeof StoriesStoryIdReadRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/read': typeof StoriesStoryIdReadRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/read'
    | '/stories/$storyId/chapters/$chapterId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/read'
    | '/stories/$storyId/chapters/$chapterId/edit'
  id:
    | '__root__'
    | '/'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/read'
    | '/stories/$storyId/chapters/$chapterId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesStoryIdEditRoute: typeof StoriesStoryIdEditRoute
  StoriesStoryIdReadRoute: typeof StoriesStoryIdReadRoute
  StoriesStoryIdChaptersChapterIdEditRoute: typeof StoriesStoryIdChaptersChapterIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/read': {
      id: '/stories/$storyId/read'
      path: '/stories/$storyId/read'
      fullPath: '/stories/$storyId/read'
      preLoaderRoute: typeof StoriesStoryIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/edit': {
      id: '/stories/$storyId/edit'
      path: '/stories/$storyId/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof StoriesStoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/chapters/$chapterId/edit': {
      id: '/stories/$storyId/chapters/$chapterId/edit'
      path: '/stories/$storyId/chapters/$chapterId/edit'
      fullPath: '/stories/$storyId/chapters/$chapterId/edit'
      preLoaderRoute: typeof StoriesStoryIdChaptersChapterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesStoryIdEditRoute: StoriesStoryIdEditRoute,
  StoriesStoryIdReadRoute: StoriesStoryIdReadRoute,
  StoriesStoryIdChaptersChapterIdEditRoute:
    StoriesStoryIdChaptersChapterIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
