/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as StoriesStoryIdIndexRouteImport } from './routes/stories.$storyId.index'
import { Route as StoriesStoryIdReadRouteImport } from './routes/stories.$storyId.read'
import { Route as StoriesStoryIdEditRouteImport } from './routes/stories.$storyId.edit'
import { Route as StoriesStoryIdChaptersNewRouteImport } from './routes/stories.$storyId.chapters.new'
import { Route as StoriesStoryIdChaptersChapterIdEditRouteImport } from './routes/stories.$storyId.chapters.$chapterId.edit'
import { Route as StoriesStoryIdChaptersChapterIdChildrenNewRouteImport } from './routes/stories.$storyId.chapters.$chapterId.children.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdIndexRoute = StoriesStoryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdReadRoute = StoriesStoryIdReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdEditRoute = StoriesStoryIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdChaptersNewRoute =
  StoriesStoryIdChaptersNewRouteImport.update({
    id: '/chapters/new',
    path: '/chapters/new',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)
const StoriesStoryIdChaptersChapterIdEditRoute =
  StoriesStoryIdChaptersChapterIdEditRouteImport.update({
    id: '/chapters/$chapterId/edit',
    path: '/chapters/$chapterId/edit',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)
const StoriesStoryIdChaptersChapterIdChildrenNewRoute =
  StoriesStoryIdChaptersChapterIdChildrenNewRouteImport.update({
    id: '/chapters/$chapterId/children/new',
    path: '/chapters/$chapterId/children/new',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/read': typeof StoriesStoryIdReadRoute
  '/stories/$storyId/': typeof StoriesStoryIdIndexRoute
  '/stories/$storyId/chapters/new': typeof StoriesStoryIdChaptersNewRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
  '/stories/$storyId/chapters/$chapterId/children/new': typeof StoriesStoryIdChaptersChapterIdChildrenNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/read': typeof StoriesStoryIdReadRoute
  '/stories/$storyId': typeof StoriesStoryIdIndexRoute
  '/stories/$storyId/chapters/new': typeof StoriesStoryIdChaptersNewRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
  '/stories/$storyId/chapters/$chapterId/children/new': typeof StoriesStoryIdChaptersChapterIdChildrenNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/read': typeof StoriesStoryIdReadRoute
  '/stories/$storyId/': typeof StoriesStoryIdIndexRoute
  '/stories/$storyId/chapters/new': typeof StoriesStoryIdChaptersNewRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
  '/stories/$storyId/chapters/$chapterId/children/new': typeof StoriesStoryIdChaptersChapterIdChildrenNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories/$storyId'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/read'
    | '/stories/$storyId/'
    | '/stories/$storyId/chapters/new'
    | '/stories/$storyId/chapters/$chapterId/edit'
    | '/stories/$storyId/chapters/$chapterId/children/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/read'
    | '/stories/$storyId'
    | '/stories/$storyId/chapters/new'
    | '/stories/$storyId/chapters/$chapterId/edit'
    | '/stories/$storyId/chapters/$chapterId/children/new'
  id:
    | '__root__'
    | '/'
    | '/stories/$storyId'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/read'
    | '/stories/$storyId/'
    | '/stories/$storyId/chapters/new'
    | '/stories/$storyId/chapters/$chapterId/edit'
    | '/stories/$storyId/chapters/$chapterId/children/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/': {
      id: '/stories/$storyId/'
      path: '/'
      fullPath: '/stories/$storyId/'
      preLoaderRoute: typeof StoriesStoryIdIndexRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/read': {
      id: '/stories/$storyId/read'
      path: '/read'
      fullPath: '/stories/$storyId/read'
      preLoaderRoute: typeof StoriesStoryIdReadRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/edit': {
      id: '/stories/$storyId/edit'
      path: '/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof StoriesStoryIdEditRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/chapters/new': {
      id: '/stories/$storyId/chapters/new'
      path: '/chapters/new'
      fullPath: '/stories/$storyId/chapters/new'
      preLoaderRoute: typeof StoriesStoryIdChaptersNewRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/chapters/$chapterId/edit': {
      id: '/stories/$storyId/chapters/$chapterId/edit'
      path: '/chapters/$chapterId/edit'
      fullPath: '/stories/$storyId/chapters/$chapterId/edit'
      preLoaderRoute: typeof StoriesStoryIdChaptersChapterIdEditRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/chapters/$chapterId/children/new': {
      id: '/stories/$storyId/chapters/$chapterId/children/new'
      path: '/chapters/$chapterId/children/new'
      fullPath: '/stories/$storyId/chapters/$chapterId/children/new'
      preLoaderRoute: typeof StoriesStoryIdChaptersChapterIdChildrenNewRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
  }
}

interface StoriesStoryIdRouteChildren {
  StoriesStoryIdEditRoute: typeof StoriesStoryIdEditRoute
  StoriesStoryIdReadRoute: typeof StoriesStoryIdReadRoute
  StoriesStoryIdIndexRoute: typeof StoriesStoryIdIndexRoute
  StoriesStoryIdChaptersNewRoute: typeof StoriesStoryIdChaptersNewRoute
  StoriesStoryIdChaptersChapterIdEditRoute: typeof StoriesStoryIdChaptersChapterIdEditRoute
  StoriesStoryIdChaptersChapterIdChildrenNewRoute: typeof StoriesStoryIdChaptersChapterIdChildrenNewRoute
}

const StoriesStoryIdRouteChildren: StoriesStoryIdRouteChildren = {
  StoriesStoryIdEditRoute: StoriesStoryIdEditRoute,
  StoriesStoryIdReadRoute: StoriesStoryIdReadRoute,
  StoriesStoryIdIndexRoute: StoriesStoryIdIndexRoute,
  StoriesStoryIdChaptersNewRoute: StoriesStoryIdChaptersNewRoute,
  StoriesStoryIdChaptersChapterIdEditRoute:
    StoriesStoryIdChaptersChapterIdEditRoute,
  StoriesStoryIdChaptersChapterIdChildrenNewRoute:
    StoriesStoryIdChaptersChapterIdChildrenNewRoute,
}

const StoriesStoryIdRouteWithChildren = StoriesStoryIdRoute._addFileChildren(
  StoriesStoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesStoryIdRoute: StoriesStoryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
